### ISSUE TITLE
Panic when downloading Twig

### ISSUE THREAD

**Issue by avorobey** [nicohman/rust-wildbow-scraper#1]
I'm getting the following reliably when trying to download Twig

Downloaded Bleeding Edge – 8.3
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
Error { kind: Url(RelativeUrlWithoutBase), url: None }', libcore/result.rs:945:5

Running freshly cloned rust-wildbow-scraper on the Linux subsystem of a Windows 10 machine.
Built w/o issues and scraped all the other books, except Twig, without issues.

The stack backtrace looks like:

[backtrace stuff]
7:core::panicking::panic_fmt at libcore/panicking.rs:92  
8: core::result::unwrap_failed   
9: rust_wildbow_scraper::download_iter
10: rust_wildbow_scraper::download_iter
[50 more lines of rust_wildbow_scraper::download_iter]

**Comment by nicohman** [comment]
Will fix when I have the opportunity to. My first instinct would be to guess that it’s related to windows subsystem, though.

**Comment by nicohman** [comment]
Never mind, it’s a bug that occurs with Linux machines too. Will check out what’s different about 8.3 later.

**Comment by nicohman** [comment]
Apparently at some time between when I last tested the scraper on twig and now, the next link on 8.3 became unusually deformed. It's been fixed now, along with the dead cover links. Tested with all available books. Let me know if it still doesn't work for some reason.
