### ISSUE TITLE
std::ops::Bound is invalid? during cargo install

### ISSUE THREAD

**Issue by johnwittle** [nicohman/rust-wildbow-scraper#13]
> Downloading ansi_term v0.11.0
>    Compiling syn v0.15.44
>    Compiling proc-macro2 v1.0.6
>    Compiling ryu v1.0.2
>    Compiling libc v0.2.65
>    Compiling byteorder v1.3.2
>    Compiling pkg-config v0.3.17
> error[E0432]: unresolved import `std::ops::Bound`
>   --> /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.17/src/lib.rs:72:16
>    |
> 72 | use std::ops::{Bound, RangeBounds};
>    |                ^^^^^ no `Bound` in `ops`
> 
> error[E0432]: unresolved import `std::ops::RangeBounds`
>   --> /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.17/src/lib.rs:72:23
>    |
> 72 | use std::ops::{Bound, RangeBounds};
>    |                       ^^^^^^^^^^^ no `RangeBounds` in `ops`
> 
> error: `dyn Trait` syntax is unstable (see issue #44662)
>    --> /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.17/src/lib.rs:143:32
>     |
> 143 |     fn cause(&self) -> Option<&dyn error::Error> {
>     |                                ^^^^^^^^^^^^^^^^
> 
> error: aborting due to 3 previous errors
> 
> error: Could not compile `pkg-config`.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `rust-wildbow-scraper v1.0.0 (file:///home/admin/rust-wildbow-scraper)`, intermediate artifacts can be found at `/home/admin/rust-wildbow-scraper/target`
> 
> Caused by:
>   build failed

I'd love to know what's going on here.

I did: `apt-get install git python curl pkg-config libssl-dev rustc cargo`
then I did: `git clone https://github.com/nicohman/rust-wildbow-scraper.git && cd rust-wildbow-scraper`
then I did: `cargo install`

on a brand new debian aws instance

got the above error

upon repeating 'cargo install' I see:

> ` % cargo install
>   Installing rust-wildbow-scraper v1.0.0 (file:///home/admin/rust-wildbow-scraper)
>     Updating registry `https://github.com/rust-lang/crates.io-index`
>    Compiling podio v0.1.6
>    Compiling vec_map v0.8.1
>    Compiling string_cache_shared v0.3.0
>    Compiling cc v1.0.47
>    Compiling matches v0.1.8
> error: `crate` in paths is experimental (see issue #45477)
>   --> /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.47/src/windows_registry.rs:16:5
>    |
> 16 | use crate::Tool;
>    |     ^^^^^
> 
> error: aborting due to previous error
> 
> error: Could not compile `cc`.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `rust-wildbow-scraper v1.0.0 (file:///home/admin/rust-wildbow-scraper)`, intermediate artifacts can be found at `/home/admin/rust-wildbow-scraper/target`
> 
> Caused by:
>   build failed`
> 

which is not the same error message

i am unfamiliar with rust and with cargo, and don't really want to debug this myself

**Comment by nicohman** [comment]
My first thought here is that you’re using an older version of rust from the repo, which would be causing these errors when compiling dependencies. Could you try installing rust using rustup and making sure you’re on the latest stable version?
