### ISSUE TITLE
Pact errors post-download.

### ISSUE THREAD

**Issue by PointMeAtTheDawn** [nicohman/rust-wildbow-scraper#23]
thread 'reductor' panicked at 'Couldn't export epub: Io { desc: "network content", op: "inspect", more: Some("Not Found") }', src/main.rs:393:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/main.rs:49:20

**Comment by PointMeAtTheDawn** [comment]
(Only fails with cover download)

**Comment by nicohman** [comment]
It looks like the cover url that was included is down now. I'll see about removing it.
