### ISSUE TITLE
Last line of Glow Worm P.1 is chopped off

### ISSUE THREAD

**Issue by steinybear** [nicohman/rust-wildbow-scraper#3]
This is the only missing line I've noticed but I don't have a way to compare the generated epub text with the text on the website.

I'll try to figure out how to set up debugging in rust tonight unless you think you know what might be causing lines to be dropped.

**Comment by steinybear** [comment]
I've found the cause of the bug.

On most pages, he put the "Next" and "Next Chapter" links inside their own <p> tags.

In P1 of Glow Worm, the last paragraph of the content shares a <p> tag with the "Next Chapter" link.

If there are any other cases of this in any of the other chapters or books, the lines will not be included in the epub.


```
<p>♦  <strong>You have <em>three</em> unread private messages from an Anonymous account.  Click <span style="text-decoration:underline;">here</span> to read.<br />
--
  | <a href="https://parahumans.wordpress.com/2017/10/21/glowworm-p-1/"><br />
  | </a>Last Chapter                                                                                               <a href="https://parahumans.wordpress.com/2017/10/24/glow-worm-p-2/">Next Chapter</a><br />
  | </strong></p>
```

**Comment by steinybear** [comment]
The fix for this is waiting for your approval in my pull request.

**Comment by nicohman** [comment]
I'm not seeing either pull request. Are you sure that you've made them?

**Comment by nicohman** [comment]
Got PR, accepted.
