### ISSUE TITLE
windows binaries

### ISSUE THREAD

**Issue by KraXen72** [nicohman/rust-wildbow-scraper#41]
please add windows (even cli are fine) binaries so that i don't have so set up rust & cargo & everything. thanks.

**Comment by nicohman** [comment]
I don't have a windows machine, so the difficulty of setting up cross-compiling isn't really worth it, especially when I don't give a lot of time to this project these days anyways. Closing as out of scope

**Comment by shankarsivarajan** [comment]
It's worth setting up rust and cargo so you can get the latest patched version, but here is my .exe as of today: [rust-wildbow-scraper-windows](https://github.com/nicohman/rust-wildbow-scraper/files/11356695/rust-wildbow-scraper.zip)

**Comment by KraXen72** [comment]
could this maybe be achieved using github actions?
