### ISSUE TITLE
number resulting epubs

### ISSUE THREAD

**Issue by KraXen72** [nicohman/rust-wildbow-scraper#46]
im pretty new to this series, so im not sure in which order to read the ebooks.
it would be good if the filenames were in this format: `1-worm.epub`, etc.  
or alternatively, if you could just let me know the order, i'll rename them myself. thanks.

**Comment by nicohman** [comment]
I'm not going to change the output format without a particular reason, especially since there's only two sequels as of right now.

**Comment by KraXen72** [comment]
@nicohman if you could just let me know the order the ebooks are supposed to be read in, i'll rename them myself. thanks.
