### ISSUE TITLE
Pale is only scraped up to 22.4

### ISSUE THREAD

**Issue by samuelmayerhofer** [nicohman/rust-wildbow-scraper#47]
When I attempt to scrape Pale, it's only scraped up to 22.4. Is there anything that can solve this issue?

**Comment by nicohman** [comment]
I just ran it with the current master and it scraped up to 24.a, which is the latest chapter - are you sure you're on the latest version? You could also try deleting your cache - the directory should be printed when you run the scraper.

**Comment by samuelmayerhofer** [comment]
> I just ran it with the current master and it scraped up to 24.a, which is the latest chapter - are you sure you're on the latest version? You could also try deleting your cache - the directory should be printed when you run the scraper.

How do I update the scraper on my system?

**Comment by nicohman** [comment]
You can run `git pull` to update your local source, followed by reinstalling with ` cargo install --path .`
