### ISSUE TITLE
some square dividers aren't center aligned

### ISSUE THREAD

**Issue by KraXen72** [nicohman/rust-wildbow-scraper#48]
on some pages, the square center dividers are properly center aligned:
![20230512_170949.jpg](https://github.com/nicohman/rust-wildbow-scraper/assets/21956756/b574045d-9dad-4a2a-9138-fb910660c835)

on other pages, it's aligned to the left:
![20230512_171006.jpg](https://github.com/nicohman/rust-wildbow-scraper/assets/21956756/6e1e3271-6a0f-4bf0-9be6-229a1fb0c514)

it would be good, if it was consistent. if i were to choose which style looks better, it's definitely the center aligned variant.

not a huge deal, but would be nicer if consistent.

**Comment by KraXen72** [comment]
the pages in photos are from interlude 8, between extermination 8.2 and 8.3 in Worm.

**Comment by jtojnar** [comment]
Thanks for reporting, opened https://github.com/nicohman/rust-wildbow-scraper/pull/49
