### ISSUE TITLE
scraper asks for awkwardly old version of reqwest

### ISSUE THREAD

**Issue by Gagis** [nicohman/rust-wildbow-scraper#5]
The old version of reqwest in your Cargo.toml depends on an old version of openssl, which is not compatible with newer versions of SSL, which makes the build fail on Arch Linux at least.

Compilation was successful upon editing .toml to include "reqwest = "0.9.3"" which was just the latest version I happened to see in cargo. I also compiled without Cargo.lock since it did not seem to be necessary.

**Comment by nicohman** [comment]
Updated. Sorry and thanks for the report!

**Comment by nicohman** [comment]
Just want to say that I also realized that gen-epub-book was depending on a bad version of openssl too, so I updated that as well just in case.
