### ISSUE TITLE
Pact issue

### ISSUE THREAD

**Issue by jaypro13** [nicohman/rust-wildbow-scraper#50]
Following errors appear when trying to download pact. Only the first chapter downloads

![image](https://github.com/nicohman/rust-wildbow-scraper/assets/94020842/c54fb7dc-038b-4717-aa33-1ed0188f6248)

**Comment by jtojnar** [comment]
Thanks for reporting, opened https://github.com/nicohman/rust-wildbow-scraper/pull/51 with a fix.
