### ISSUE TITLE
Why is Pale 122 MB?

### ISSUE THREAD

**Issue by MultiKoopa** [nicohman/rust-wildbow-scraper#54]
Is there any way to reduce this file size?

**Comment by TheMetalCenter** [comment]
Pale has a lot of images. You could edit the book in Calibre and delete the images all at once by selecting them in the left side panel. There may be an option for it when converting as well. On Nov 10, 2023, at 4:22 AM, MultiKoopa ***@***.***> wrote:﻿
Is there any way to reduce this file size?

**Comment by MultiKoopa** [comment]
> Pale has a lot of images. You could edit the book in Calibre and delete the images all at once by selecting them in the left side panel. There may be an option for it when converting as well. 

Are the images particularly important to the story?

**Comment by jtojnar** [comment]
They are mostly accompanying materials – not necessary for plot but can give you more context or clarify the story. Included is stuff like the girls’ notes, book excepts, maps, see https://palewebserial.wordpress.com/extra-material/

There are also some illustrations at the beginning of each chapter which are not necessary but they are not too big.

We could probably add flags for skipping the bonus material chapters and removing chapter illustrations.
