### ISSUE TITLE
Covers not working?

### ISSUE THREAD

**Issue by bittwiddlers** [nicohman/rust-wildbow-scraper#6]
I am able to download the covers using the urls that the program prints out and those look fine.I get this error

`{314}: rust-wildbow-scraper --worm
Would you like to include a cover for Worm? Cover URL is https://i.imgur.com/g0fLbQ1.jpg. If it cannot be downloaded, program will not exit gracefully.(y/n)y
thread 'reductor' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', libcore/result.rs:945:5`

whether I select 'y' or 'n'. If I do the "--yes" arg then the book is created but no cover exists. Do the covers work fine for you?

**Comment by nicohman** [comment]
Fixed. Sorry for not realizing this before! Should work just fine now. Let me know if you have any more problems!
