### ISSUE TITLE
Generated epub files are DRM-protected somehow?

### ISSUE THREAD

**Issue by maksverver** [nicohman/rust-wildbow-scraper#7]
I generated epubs for Glow-worm and Ward. When I open themon my Kobo e-reader, it shows an error message:

“Your eReader is not authorized to open this book.

This book is protected by Adobe Digital Rights Management (DRM). You need to re-authorize your eReader with your Adobe ID using Adobe Digital Editions (ADE). Please visit kobo.com/help for more information.”

**Comment by maksverver** [comment]
FWIW, reformatting the generated epub files with [pandoc](https://pandoc.org) fixed the problem for me.

Example:

    % pandoc ward.epub -o ward-fixed.epub

**Comment by nicohman** [comment]
This is weird & shouldn't be happening. I just tried generating a new one, and I could open it in calibre just fine. Is the issue only on your e-reader?

**Comment by maksverver** [comment]
It's only on my Kobo e-reader.

It seems like the problem is caused by the ordering of the files in the epub file (which is really just a .zip file).

I figured this out problem using the EPUB Validator at http://validator.idpf.org, which gives an error: “Mimetype file entry is missing or is not the first file in the archive.” (there are some other errors too, but they seem less serious).

And indeed, I could fix the epub by unzipping it and recreating the zip file with the `mimetype` file at the start:

    % unzip glow-worm.epub
    % zip -X fixed.epub mimetype META-INF/container.xml content.opf toc.ncx ./*.html

**Comment by nicohman** [comment]
First of all, thanks for the detailed info. It looks like this is an issue with the epub library I'm using, and I opened a pull request to fix that [here](https://github.com/nabijaczleweli/gen-epub-book.rs/pull/4). When it's accepted, the issue shoudl be fixed. Thanks again for your help!

**Comment by maksverver** [comment]
Sounds good. Thanks for following up! Feel free to close this issue when you like.

**Comment by nicohman** [comment]
The pull request was merged and I updated gen-epub-book in b7bcdad. Closing.
