### ISSUE TITLE
Seems like I can not properly install the scraper...

### ISSUE THREAD

**Issue by lebrouhaha** [nicohman/rust-wildbow-scraper#9]
Is there maybe a problem with the command?

I just installed Rust (and Cargo at the same time) so I could run the command to install the scraper, and it downloads properly but it seems like I can not install it, or at least, I don't know how to use the commands. Maybe I'm simply doing something wrong.

I'm not a coder, sorry, I barely know how to run script in the terminal.

I'm on a Macbook 15" late 2013, OSX 10.14.2.

This is what I got on my terminal window :

> MacBook-Pro-de-lebrouhaha:~ lebrouhaha$ git clone https://github.com/nicohman/rust-wildbow-scraper.git && cd rust-wildbow-scraper
> Cloning into 'rust-wildbow-scraper'...
> remote: Enumerating objects: 161, done.
> remote: Total 161 (delta 0), reused 0 (delta 0), pack-reused 161
> Receiving objects: 100% (161/161), 72.99 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (78/78), done.
> MacBook-Pro-de-lebrouhaha:rust-wildbow-scraper lebrouhaha$ 
> MacBook-Pro-de-lebrouhaha:rust-wildbow-scraper lebrouhaha$ cargo install --path .
> -bash: cargo: command not found
> MacBook-Pro-de-lebrouhaha:rust-wildbow-scraper lebrouhaha$ cargo install --path
> -bash: cargo: command not found

**Comment by nicohman** [comment]
This isn't an issue with the scraper, you just don't have cargo or the cargo bin folder n your $PATH. Once you set that properly, it should work.
